//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KURSOVAYA____
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dolzhnost
    {
        public Dolzhnost()
        {
            this.Sotrudniki = new HashSet<Sotrudniki>();
        }
    
        public int Id_dolzhnost { get; set; }
        public string Naimenovanie_dolzhnost { get; set; }
        public string Uroven_dolzhnosti { get; set; }
        public string Status_dolzhnosti { get; set; }
    
        public virtual ICollection<Sotrudniki> Sotrudniki { get; set; }
    }
}
