//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KURSOVAYA____
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lichnie_dannie
    {
        public int Id_dannih { get; set; }
        public Nullable<int> Id_sotrudnika { get; set; }
        public Nullable<System.DateTime> Data_rozhdeniya { get; set; }
        public string Adres { get; set; }
        public string Pol { get; set; }
        public Nullable<System.DateTime> Data_priema_na_rab { get; set; }
        public string INN { get; set; }
        public string Nomer_medpolisa { get; set; }
        public string SNILS { get; set; }
    
        public virtual Sotrudniki Sotrudniki { get; set; }
    }
}
