//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KURSOVAYA____
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Dolzhnost> Dolzhnost { get; set; }
        public DbSet<Lichnie_dannie> Lichnie_dannie { get; set; }
        public DbSet<Otdeli> Otdeli { get; set; }
        public DbSet<RaschetZP> RaschetZP { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<Sotrudniki> Sotrudniki { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
