//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KURSOVAYA____
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaschetZP
    {
        public int Id_zp { get; set; }
        public Nullable<int> Id_sotrudnika { get; set; }
        public Nullable<int> Stavka { get; set; }
        public Nullable<int> Kol_vo_chasov { get; set; }
        public Nullable<int> Summa_k_viplate_do { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> Summa_k_viplate_posle { get; set; }
    
        public virtual Sotrudniki Sotrudniki { get; set; }
    }
}
