//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KURSOVAYA____
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudniki
    {
        public Sotrudniki()
        {
            this.Lichnie_dannie = new HashSet<Lichnie_dannie>();
            this.RaschetZP = new HashSet<RaschetZP>();
        }
    
        public int Id_sotrudnika { get; set; }
        public string Familiya { get; set; }
        public string Imya { get; set; }
        public string Otchestvo { get; set; }
        public Nullable<int> Id_dolzhnost { get; set; }
        public string Photo { get; set; }
        public Nullable<int> Id_otdela { get; set; }
    
        public virtual Dolzhnost Dolzhnost { get; set; }
        public virtual ICollection<Lichnie_dannie> Lichnie_dannie { get; set; }
        public virtual Otdeli Otdeli { get; set; }
        public virtual ICollection<RaschetZP> RaschetZP { get; set; }
    }
}
